# version: '3.8'

services:

  db:
    image: postgis/postgis:16-3.5
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 6543
      POSTGRES_DB: fgeovisor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fgeovisor"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - backend
    # profiles: ["default", "test"]

  django:
    build:
      context: .
      dockerfile: fgeovisor/Dockerfile
    restart: always
    environment:
      DEBUG: true
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 6543
      POSTGRES_DB_NAME: fgeovisor
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SUPERUSER_PASSWORD: 1234
      DJANGO_SUPERUSER_EMAIL: root@yanyan.ru
      ALLOWED_HOSTS: localhost, 127.0.0.1
    ports:
      - 8000:8000
    networks:
      - backend
    develop:
      watch:
        - action: sync
          path: /fgeovisor
          target: /usr/src/app
          ignore:
            - /fgeovisor/images/IMAGES/
    depends_on:
      db:
        condition: service_healthy
    # profiles: ["default", "test"]

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
    - DJANGO_PORT=8000
    networks:
      - backend
    depends_on:
      - django
    # volumes:
    #   - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
    #   - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key
    # profiles: ["default", "test"]

networks:
  backend:

volumes:
  postgres_data:
    driver: local